/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.shareok.data.sagedata;

import java.util.Date;

/**
 *
 * @author Tao Zhao
 */
public class SageJournalData {
    private String peerReviewNotes;   
    private String language;                                               
    private String publisher;                                              
    private String peerReview;                                                  
    private String rights;                            
    private String rightsUri;        
    private boolean rightsRequestable;    

    private String doi;                                                                             
    private String uri;                                                                             
    private String type;                                                                            
    private String title;         
    private String citation;
    private String relationUri;
    private String abstractText;                                                                    
    private String acknowledgements;    
    private String authorContributions;
    private String isPartOfSeries;                                                                  
    
    private Date dateAvailable;
    private Date dateIssued;
    
    private String[] authors;                                                                  
    private String[] subjects;   

    /**
     *
     * @return dc.description.peerreviewnotes
     */
    public String getPeerReviewNotes() {
        return peerReviewNotes;
    }

    /**
     *
     * @return dc.language.iso;
     */
    public String getLanguage() {
        return language;
    }

    /**
     *
     * @return dc.publisher
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     *
     * @return dc.description.peerreview
     */
    public String getPeerReview() {
        return peerReview;
    }

    /**
     *
     * @return dc.rights 
     */
    public String getRights() {
        return rights;
    }

    /**
     *
     * @return dc.relation.uri
     */
    public String getRightsUri() {
        return rightsUri;
    }

    /**
     *
     * @return dc.rights.requestable
     */
    public boolean isRightsRequestable() {
        return rightsRequestable;
    }

    /**
     *
     * @return dc.identifier.doi
     */
    public String getDoi() {
        return doi;
    }

    /**
     *
     * @return dc.identifier.uri 
     * http://dx.doi.org/10.1371/journal.pone.0088732
     * or 
     * http://hdl.handle.net/1969.1/152287, this should be generated by DSpace
     */
    public String getUri() {
        return uri;
    }

    /**
     *
     * @return dc.type
     */
    public String getType() {
        return type;
    }

    /**
     *
     * @return dc.title
     */
    public String getTitle() {
        return title;
    }

    /**
     *
     * @return dc.identifier.citation
     */
    public String getCitation() {
        return citation;
    }

    /**
     *
     * @return dc.relation.uri
     */
    public String getRelationUri() {
        return relationUri;
    }

    /**
     *
     * @return dc.description.abstract
     */
    public String getAbstractText() {
        return abstractText;
    }

    /**
     *
     * @return dc.description
     */
    public String getAcknowledgements() {
        return acknowledgements;
    }

    /**
     *
     * @return dc.description
     */
    public String getAuthorContributions() {
        return authorContributions;
    }

    /**
     *
     * @return dc.relation.ispartofseries
     */
    public String getIsPartOfSeries() {
        return isPartOfSeries;
    }

    /**
     *
     * @return dc.data
     */
    public Date getDateAvailable() {
        return dateAvailable;
    }

    /**
     *
     * @return dc.date
     */
    public Date getDateIssued() {
        return dateIssued;
    }

    /**
     *
     * @return dc.contributor.author
     */
    public String[] getAuthors() {
        return authors;
    }

    /**
     *
     * @return dc.subject
     */
    public String[] getSubjects() {
        return subjects;
    }

    /**
     *
     * @param peerReviewNotes
     */
    public void setPeerReviewNotes(String peerReviewNotes) {
        this.peerReviewNotes = peerReviewNotes;
    }

    /**
     *
     * @param language
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     *
     * @param publisher
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     *
     * @param peerReview
     */
    public void setPeerReview(String peerReview) {
        this.peerReview = peerReview;
    }

    /**
     *
     * @param rights
     */
    public void setRights(String rights) {
        this.rights = rights;
    }

    /**
     *
     * @param rightsUri
     */
    public void setRightsUri(String rightsUri) {
        this.rightsUri = rightsUri;
    }

    /**
     *
     * @param rightsRequestable
     */
    public void setRightsRequestable(boolean rightsRequestable) {
        this.rightsRequestable = rightsRequestable;
    }

    /**
     *
     * @param doi
     */
    public void setDoi(String doi) {
        this.doi = doi;
    }

    /**
     *
     * @param uri
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     *
     * @param type
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     * @param citation
     */
    public void setCitation(String citation) {
        this.citation = citation;
    }

    /**
     *
     * @param relationUri
     */
    public void setRelationUri(String relationUri) {
        this.relationUri = relationUri;
    }

    /**
     *
     * @param abstractText
     */
    public void setAbstractText(String abstractText) {
        this.abstractText = abstractText;
    }

    /**
     *
     * @param acknowledgements
     */
    public void setAcknowledgements(String acknowledgements) {
        this.acknowledgements = acknowledgements;
    }

    /**
     *
     * @param authorContributions
     */
    public void setAuthorContributions(String authorContributions) {
        this.authorContributions = authorContributions;
    }

    /**
     *
     * @param isPartOfSeries
     */
    public void setIsPartOfSeries(String isPartOfSeries) {
        this.isPartOfSeries = isPartOfSeries;
    }

    /**
     *
     * @param dateAvailable
     */
    public void setDateAvailable(Date dateAvailable) {
        this.dateAvailable = dateAvailable;
    }

    /**
     *
     * @param dateIssued
     */
    public void setDateIssued(Date dateIssued) {
        this.dateIssued = dateIssued;
    }

    /**
     *
     * @param authors
     */
    public void setAuthors(String[] authors) {
        this.authors = authors;
    }

    /**
     *
     * @param subjects
     */
    public void setSubjects(String[] subjects) {
        this.subjects = subjects;
    }
    
}
