<%-- 
    Document   : plosDataUpload
    Created on : Jan 25, 2016, 12:32:47 AM
    Author     : Tao Zhao
--%>

    <%@ include file="header.jsp" %>   
    <%@ include file="navTab.jsp" %>     
    
    <c:set var="string1" value="${publisher}"/>
    <c:set var="publisherUpCase" value="${fn:toUpperCase(string1)}" />
    
    <c:set var="uploadStr1" value="Upload a CSV or Excel file to generate the SAF package:"/>
    <c:set var="uploadStr2" value="Upload the zip file to generate the SAF package:"/>
    
    <div class="container">
        <div class="jumbotron">
            <div class="panel panel-primary">
                <div class="panel-heading"><h4>Process the ${publisher} Publications:</h4></div>
                <div class="panel-body">
                    <c:if test="${publisher == 'ouhistory'}">
                        <h3>${uploadStr2}</h3>
                        <c:set var="dataType" value="safpackage"/>
                    </c:if>
                    
                    <c:if test="${publisher != 'ouhistory'}">
                        <h3>${uploadStr1}</h3>
                        <c:set var="dataType" value="journal"/>
                    </c:if>
                        
                        <form action="/webserv/dspace/${dataType}/${publisher}/upload" method="post" enctype="multipart/form-data">
                        <input type="file" name="file" />
                        <br />
                        <!-- <button type="button" class="btn btn-primary btn-md">Upload File</button> -->
                        <input type="submit" class="btn btn-info btn-primary loading-btn" value="Generate the Simple Archive Format">
                        <%@ include file="spining.jsp" %>
                        </form>
                    <BR>
                    <BR>
                    <c:if test="${publisher != 'ouhistory'}">
                    <div class="download-link-div">
                        <h4>Download the original uploaded file and the DSpace simple archive format files:</h4>
                        <a href="${oldFile}" class="btn btn-info btn-sm" role="button">Download the Uploaded File</a>
                        &nbsp;&nbsp;
                        <a href="${loadingFile}" class="btn btn-info btn-sm" role="button">Download the Simple Archive Format</a>
                        <BR><BR>
                    </div>
                    <BR>
                    <div class="download-link-div">
                         <h4>Sample dublin_core metadata file can be downloaded here:</h4>
                         <a href="${sampleDublinCore}" class="btn btn-info btn-sm" role="button">Sample Dublin Core File</a>
                    </div>
                    <BR>
                    </c:if>
                </div>
            </div>
            
        </div>
    </div>
    
    <c:if test="${publisher != 'ouhistory'}">
        <!-- The SSH DSpace section required a upload file path, which maybe sent by the backend controller or generated by backend controller after submitted -->
        <%@ include file="sshDspaceJournalData.jsp" %>     
    </c:if>
</body>
</html>
